### ISSUE TITLE
[Assignment 5] IOException while Integration Test

### ISSUE THREAD

**Issue by juuice-lee** [kaist-cp/cs492-uarch#96]
Hello! I implemented the mesh code and tried to run integration test, but java.io.IOException is occurred. 

I just tried to build emulator with` python3 scripts/gemmini/main.py build -c mesh`

```
java.io.IOException: User limit of inotify instances reached or too many open files
        at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:62)
        at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
        at com.swoval.files.RegisterableWatchServices$RegisterableWatchServiceImpl.<init>(RegisterableWatchServices.java:34)
        at com.swoval.files.RegisterableWatchServices.get(RegisterableWatchServices.java:21)
        at com.swoval.files.PlatformWatcher.make(PlatformWatcher.java:11)
        at com.swoval.files.PathWatchers.get(PathWatchers.java:85)
        at com.swoval.files.FileTreeRepositories.get(FileTreeRepositories.java:64)
        at com.swoval.files.FileTreeRepositories.get(FileTreeRepositories.java:32)
        at sbt.internal.nio.FileTreeRepositoryImpl.<init>(FileTreeRepositoryImpl.scala:47)
        at sbt.internal.nio.FileTreeRepository$.default(FileTreeRepository.scala:40)
        at sbt.BuiltinCommands$.$anonfun$setupGlobalFileTreeRepository$1(Main.scala:984)
        at sbt.BuiltinCommands$.$anonfun$doLoadProject$5(Main.scala:976)
        at sbt.Project$.setProject(Project.scala:501)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:976)
        at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:914)
        at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
        at sbt.Command$.process(Command.scala:189)
        at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:245)
        at sbt.MainLoop$.processCommand(MainLoop.scala:278)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.MainLoop$.next(MainLoop.scala:163)
        at sbt.MainLoop$.run(MainLoop.scala:144)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
        at sbt.io.Using.apply(Using.scala:27)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
        at sbt.MainLoop$.runLogged(MainLoop.scala:42)
        at sbt.StandardMain$.runManaged(Main.scala:223)
        at sbt.xMain$.$anonfun$run$11(Main.scala:133)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:578)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:358)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:568)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:568)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:358)
        at sbt.xMain$.withStreams$1(Main.scala:87)
        at sbt.xMain$.run(Main.scala:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.io.IOException: User limit of inotify instances reached or too many open files
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
make: *** [/tmp/chipyard/common.mk:110: /tmp/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.fir] Error 1
```
This is the detail of the error message.
Can I get some help how to handle this error? Thank you

**Comment by minseongg** [comment]
It was the problem of server configuration, and we have fixed it. Sorry for the inconvenience.

Could you please try again?

If it generates compilation error, you may need to run below commands before run the integration test scripts:

```bash
cargo clean
cargo build -p hazardflow-macro
```

**Comment by juuice-lee** [comment]
Now it is working! Thank you :D
